# -*- coding: utf-8 -*-
"""Python_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLla7afFRPtAIxLm3ULvu4G8i8HhNQfz

**Python Task:** Employee Workforce Data Analysis

**Objective:** Analyze employee data using the Pandas library by performing basic statistical analysis and generating workforce insights.

**Prompt Used:**

"Write a Python program using the Pandas library to create an employee dataset with the columns Employee_ID, Name, Department, Age, and Salary. Display the dataset, calculate the average age and average salary, identify the employees with the highest and lowest salaries, count employees in each department, display the total number of employees, filter employees whose salary is greater than 50,000, calculate the average salary by department using groupby(), and display the names of all employees with appropriate output headings."
"""

import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Riya", "Rahul", "Sneha", "Kiran"],
    "Department": ["HR", "IT", "Finance", "IT", "Sales"],
    "Age": [25, 30, 28, 35, 27],
    "Salary": [40000, 55000, 50000, 70000, 45000]
}

df = pd.DataFrame(data)

print("Employee Data")
print(df)

print("\nAverage Age:", df["Age"].mean())

print("Average Salary:", df["Salary"].mean())

print("\nHighest Salary:")
print(df[df["Salary"] == df["Salary"].max()])

print("\nLowest Salary:")
print(df[df["Salary"] == df["Salary"].min()])

print("\nDepartment-wise Employee Count:")
print(df["Department"].value_counts())

print("\nTotal Employees:", len(df))

print("\nEmployees with Salary greater than 50000:")
print(df[df["Salary"] > 50000])

print("\nAverage Salary by Department:")
print(df.groupby("Department")["Salary"].mean())

print("\nEmployee Names:")
print(df["Name"])

