# -*- coding: utf-8 -*-
"""SQL_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B71ZefpUHYKrF2a4RtgbvxOAhS8Br5VM

**SQL Task:** Employee Database Management and Analysis

**Objective:** Create an employee database, insert sample employee records, and perform SQL operations to retrieve and analyze employee information.

**Prompt Used:**

"Write a Python program using the sqlite3 library to create an SQLite database with an Employees table containing Employee_ID, Name, Department, Age, and Salary. Insert sample employee records into the table, execute SQL queries to display all employee details, calculate salary statistics (average, highest, and lowest salary), count employees department-wise, retrieve records based on conditions such as salary and age, and present the query results in a clear and readable format."
"""

import sqlite3
import pandas as pd

# Connect to an in-memory SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# SQL DDL and DML statements
setup_sql = """
CREATE TABLE Employees (
    Employee_ID INT PRIMARY KEY,
    Name VARCHAR(50),
    Department VARCHAR(30),
    Age INT,
    Salary INT
);

INSERT INTO Employees VALUES
(101,'Amit','HR',25,40000),
(102,'Riya','IT',30,55000),
(103,'Rahul','Finance',28,50000),
(104,'Sneha','IT',35,70000),
(105,'Kiran','Sales',27,45000);
"""

# Execute setup SQL
cursor.executescript(setup_sql)
conn.commit()
print("Database and table 'Employees' created, and data inserted successfully.\n")

# List of SQL queries to execute and display results
queries = [
    ("Display All Employees", "SELECT * FROM Employees;"),
    ("Average Salary", "SELECT AVG(Salary) AS Average_Salary FROM Employees;"),
    ("Highest Salary", "SELECT MAX(Salary) AS Highest_Salary FROM Employees;"),
    ("Lowest Salary", "SELECT MIN(Salary) AS Lowest_Salary FROM Employees;"),
    ("Department-wise Employee Count", "SELECT Department, COUNT(*) AS Employee_Count FROM Employees GROUP BY Department;"),
    ("Employees with Salary Greater Than 50000", "SELECT * FROM Employees WHERE Salary > 50000;"),
    ("Employees Older Than 28", "SELECT * FROM Employees WHERE Age > 28;")
]

# Execute each query and print results
for title, query in queries:
    print(f"--- {title} ---")
    try:
        df = pd.read_sql_query(query, conn)
        print(df.to_markdown(index=False))
    except pd.io.sql.DatabaseError as e:
        print(f"Error executing query: {e}")
    print("\n")

# Close the connection
conn.close()

import sqlite3

# Create/connect to database
conn = sqlite3.connect("employee.db")
cursor = conn.cursor()

# Create table
cursor.execute("""
CREATE TABLE Employees1(
    Employee_ID INTEGER PRIMARY KEY,
    Name TEXT,
    Department TEXT,
    Age INTEGER,
    Salary INTEGER
)
""")

# Insert data
cursor.execute("INSERT INTO Employees1 VALUES (101,'Amit','HR',25,40000)")
cursor.execute("INSERT INTO Employees1 VALUES (102,'Riya','IT',30,55000)")
cursor.execute("INSERT INTO Employees1 VALUES (103,'Rahul','Finance',28,50000)")

conn.commit()

# Query data
cursor.execute("SELECT * FROM Employees1")

for row in cursor.fetchall():
    print(row)

conn.close()

